name: drawingai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_drawing_board: ^0.5.0
  get: 4.6.6
  font_awesome_flutter: ^10.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    # - assets/logo/
    - assets/images/
  uses-material-design: true

